{
	"version": "1.0.0.17-beta",
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"Sprite Images/vpad-sheet0.png",
		"Sprite Images/hpbackground.png",
		"Sprite Images/hpbar.png",
		"Sprite Images/krbar.png",
		"Sprite Images/uiact-sheet0.png",
		"Sprite Images/uifight-sheet0.png",
		"Sprite Images/uiitem-sheet0.png",
		"Sprite Images/uimercy-sheet0.png",
		"Sprite Images/combatzone.png",
		"Sprite Images/combatzoneborder.png",
		"Sprite Images/combatzoneclipper.png",
		"Sprite Images/target-sheet0.png",
		"Sprite Images/hp-sheet0.png",
		"Sprite Images/kr-sheet0.png",
		"Sprite Images/targetchoice-sheet0.png",
		"Sprite Images/strike-sheet0.png",
		"Sprite Images/combatzoneunclipper.png",
		"Sprite Images/sanshead-sheet0.png",
		"Sprite Images/sanshead-sheet1.png",
		"Sprite Images/sansbody-sheet0.png",
		"Sprite Images/sansbody-sheet1.png",
		"Sprite Images/sanslegs-sheet0.png",
		"Sprite Images/sanssweat-sheet0.png",
		"Sprite Images/sanstorso-sheet0.png",
		"Sprite Images/speechbubble-sheet0.png",
		"Sprite Images/boneh.png",
		"Sprite Images/bonev.png",
		"Sprite Images/gasterblast1.png",
		"Sprite Images/gasterblaster-sheet0.png",
		"Sprite Images/gasterblaster-sheet1.png",
		"Sprite Images/platform1.png",
		"Sprite Images/platform2.png",
		"Sprite Images/bonestabv.png",
		"Sprite Images/bonestabh.png",
		"Sprite Images/bonestabwarn.png",
		"Sprite Images/menubonebottom-sheet0.png",
		"Sprite Images/gasterblasthit.png",
		"Sprite Images/battlefont.png",
		"Sprite Images/sansfont.png",
		"Sprite Images/defaultfont.png",
		"Sprite Images/damagefont.png",
		"Sprite Images/toucha-sheet0.png",
		"Sprite Images/toucha-sheet1.png",
		"Sprite Images/touchb-sheet0.png",
		"Sprite Images/touchb-sheet1.png",
		"Sprite Images/touchdpad-sheet0.png",
		"Sprite Images/playerheart-sheet0.png",
		"Sprite Images/playerheart-sheet1.png",
		"Sprite Images/menuitem-sheet0.png",
		"Sprite Images/heartshard-sheet0.png",
		"Sprite Images/heartshard-sheet1.png",
		"Sprite Images/heartshard-sheet2.png",
		"Sprite Images/playerhitbox-sheet0.png",
		"Music Files/ding.ogg",
		"Music Files/playerfight.ogg",
		"Music Files/playerdamaged.ogg",
		"Music Files/sansspeak.ogg",
		"Music Files/gasterblaster.ogg",
		"Music Files/bonestab.ogg",
		"Music Files/warning.ogg",
		"Music Files/heartshatter.ogg",
		"Music Files/gasterblast.ogg",
		"Music Files/flash.ogg",
		"Music Files/slam.ogg",
		"Music Files/menuselect.ogg",
		"Music Files/heartsplit.ogg",
		"Music Files/menucursor.ogg",
		"Music Files/battletext.ogg",
		"Music Files/playerheal.ogg",
		"Music Files/gasterblast2.ogg",
		"Music Files/mus_zz_megalovania.ogg",
		"icon.png",
		"loading-logo.png",
		"sans_intro.csv",
		"sans_bonegap1.csv",
		"sans_bonegap2.csv",
		"sans_bluebone.csv",
		"sans_platforms1.csv",
		"sans_platforms2.csv",
		"sans_platforms3.csv",
		"sans_platforms4.csv",
		"sans_platformblaster.csv",
		"sans_platforms4hard.csv",
		"sans_boneslideh.csv",
		"sans_bonegap1fast.csv",
		"sans_platformblasterfast.csv",
		"sans_spare.csv",
		"sans_bonestab1.csv",
		"sans_bonestab2.csv",
		"sans_boneslidev.csv",
		"sans_multi1.csv",
		"sans_randomblaster1.csv",
		"sans_multi2.csv",
		"sans_randomblaster2.csv",
		"sans_bonestab3.csv",
		"sans_multi3.csv",
		"sans_final.csv"
	]
}
